# config.py

BASE_URL = "https://sandbox.api.mastercard.com"
CONSUMER_KEY = "REPLACE WITH CONSUMER KEY"
SECRET_FILE = "REPLACE WITH THE .P12 FILE"
PASS_CODE = "REPLACE WITH THE PASSCODE TO ACCESS YOUR P12 FILE"
PARTNER_ID="SANDBOX_1234567"
CLIENT_PASSCODE = "REPLACE WITH THE PASSCODE CREATED WHILE CREATING THE DECRYPTION CERT"
